version: '3.1'

services:
  db:
    container_name: pg-prod
    image: postgres:9.6
    networks:
      - prod_net_back
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vuttr
    volumes:
      - prod_postgresql:/var/lib/postgresql
      - prod_postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - prod_net_back
    ports:
      - 6379:6379

  app:
    container_name: vuttr-app
    image: vuttr:1.0
    build:
      context: .
    networks:
      - prod_net_back
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

networks:
  prod_net_back:

volumes:
  prod_postgresql:
  prod_postgresql_data:
