version: '3.1'

services:
  db:
    container_name: pg-prod
    image: postgres:9.6
    networks:
      - prod_net_back
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vuttr
    volumes:
      - prod_postgresql:/var/lib/postgresql
      - prod_postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    container_name: vuttr-app
    image: vuttr:1.0
    build:
      context: .
    networks:
      - prod_net_back
    env_file:
      - .env
    # environment:
    #   - POSTGRES_HOST=db
    #   - DATABASE_PORT=5432
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASS=docker
    #   - DATABASE_UPDATE=none
    #   - POSTGRES_NAME=vuttr
    ports:
      - 3000:3000
    depends_on:
      - db

networks:
  prod_net_back:

volumes:
  prod_postgresql:
  prod_postgresql_data:
